// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAC5dipaRxPeJlaMmxFH1gNuO-6tcyywE',
    appId: '1:340182511941:web:f73da66bffa86dcdef8e2c',
    messagingSenderId: '340182511941',
    projectId: 'device-streaming-a1ecfe67',
    authDomain: 'device-streaming-a1ecfe67.firebaseapp.com',
    storageBucket: 'device-streaming-a1ecfe67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxf9ZCDJ6-xe4cB6pIEz6zWYz3StcF2K4',
    appId: '1:340182511941:android:31e664c58ccd958eef8e2c',
    messagingSenderId: '340182511941',
    projectId: 'device-streaming-a1ecfe67',
    storageBucket: 'device-streaming-a1ecfe67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wvJ1LrZBG3S5EsWin76unw9SQ-m04ww',
    appId: '1:340182511941:ios:e2d45800731edad8ef8e2c',
    messagingSenderId: '340182511941',
    projectId: 'device-streaming-a1ecfe67',
    storageBucket: 'device-streaming-a1ecfe67.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wvJ1LrZBG3S5EsWin76unw9SQ-m04ww',
    appId: '1:340182511941:ios:e2d45800731edad8ef8e2c',
    messagingSenderId: '340182511941',
    projectId: 'device-streaming-a1ecfe67',
    storageBucket: 'device-streaming-a1ecfe67.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAC5dipaRxPeJlaMmxFH1gNuO-6tcyywE',
    appId: '1:340182511941:web:f5bda4f6a103c4f2ef8e2c',
    messagingSenderId: '340182511941',
    projectId: 'device-streaming-a1ecfe67',
    authDomain: 'device-streaming-a1ecfe67.firebaseapp.com',
    storageBucket: 'device-streaming-a1ecfe67.firebasestorage.app',
  );
}
